#! /bin/bash

python lie.py

cd output

# Typeset output
if [ $? -eq 0 ]; then
  echo "Lie succeeded"
  pdflatex output >/dev/null 2>&1
else
  echo "Lie failed"
  exit
fi

# Open output
if [ $? -eq 0 ]; then
  echo "Latex succeeded"
  open output.pdf
else
  echo "Latex failed"
  exit
fi

# Build graph
if [ $? -eq 0 ]; then
  dot -Tpdf grid.dot -o grid.pdf >/dev/null 2>&1
fi

# Open graph
if [ $? -eq 0 ]; then
  echo "Dot succeeded"
  open grid.pdf
else
  echo "Dot failed"
  exit
fi
